CREATE TABLE Greatests
(key VARCHAR(32) PRIMARY KEY,
x INTEGER,
y INTEGER,
z INTEGER);

INSERT INTO Greatests VALUES('A',1,2,3);
INSERT INTO Greatests VALUES('B',5,5,2);
INSERT INTO Greatests VALUES('C',4,7,1);
INSERT INTO Greatests VALUES('D',3,3,8);